### ISSUE TITLE
External tables missing when using inspect or MetaData

### ISSUE THREAD

**Issue by ynncgn** [googleapis/python-bigquery-sqlalchemy#332]
Hello,

when extracting metadata for all tables, eg the names, using inspect() or MetaData reflect() on the created engine, external tables are being ignored.

#### Environment details

  - OS type and version: macOS 11.5 20G71 x86_64
  - Python version: 3.9.7
  - pip version: 21.2.4
  - `sqlalchemy-bigquery` version: 1.1.0

#### Steps to reproduce

  1. `engine = create_engine("bigquery://<project name>/<dataset>")`
  2. `inspector = inspect(engine)`
  3. `[print(table_name) for table_name in inspector.get_table_names()]`
  
  or

  3. `m = MetaData()`
  3. `m.reflect(engine)`
  3. `[print(table.name) for table in m.tables.values()]`

**Comment by tswast** [comment]
By external tables, you mean these? https://cloud.google.com/bigquery/docs/external-tables

I suspect it's because the [table "type" property](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#Table.FIELDS.type) value is reported as `EXTERNAL`, but currently we're only looking for `TABLE` in

https://github.com/googleapis/python-bigquery-sqlalchemy/blob/06c3bcc2014b5cd974a4744d53a3f6b33d67406a/sqlalchemy_bigquery/base.py#L1071

Related: I suspect `MATERIALIZED_VIEW` needs to be included in the `get_view_names` method.

**Comment by ynncgn** [comment]
> By external tables, you mean these? https://cloud.google.com/bigquery/docs/external-tables

Yes, those ones exactly!
