### ISSUE TITLE
don't enforce "use_labels = True"

### ISSUE THREAD

**Issue by sagydr** [googleapis/python-bigquery-sqlalchemy#78]
`BigQueryCompiler.visit_select` sets `args[0].use_labels = True`
in my project for example this is unneeded and changes all column names.
Please either:
1. provider a way to ignore that assignment
2. provide a way to "translate" back column name as label to its original name

![image](https://user-images.githubusercontent.com/9664064/103279264-0fb0b500-49d6-11eb-800d-4eb8b41be602.png)

**Comment by ibnbay99** [comment]
It's important when integrate with `dask.read_sql_table`, when we must fill `index_col` in bigquery table.
The column will change when going to pandas dataframe, pandas doesn't get the column index.
Because the column has be change, ex: in query select a column alias will be `[dataset_name]_[table_name]_[column_name]`

**Comment by jimfulton** [comment]
We're going to stop forcing labels. :)
