### ISSUE TITLE
Select Condition based on UNNEST

### ISSUE THREAD

**Issue by aczire** [googleapis/python-bigquery-sqlalchemy#935]
I was trying to select rows from a BigQuery view based on a condition which is inside an array of structures, 
Below is the SQL query 
```
        SELECT id, enId, versionId, code_coding
        FROM `some.schema_views.table`, UNNEST(code_coding) AS cc
        WHERE (cc.code, cc.display) = ('H', 'BLAST')
        LIMIT 100
```
 Below is my failed attempt to write the same in SQLAlchemy   
```
        from sqlalchemy.sql.expression import cast
        from sqlalchemy import String, func
        code_coding = db.query(func.unnest(self.model.code_coding)).subquery()
        conditions.append(
            and_(cast(code_coding.c.code, String) == "H", cast(code_coding.c.display, String) == "BLAST")
        )
```

It says `c.code` is not found. Any idea? Thanks ahead!

**Comment by kiraksi** [comment]
@aczire The core problem seems to stem from how SQLAlchemy ORM constructs handles structures within arrays and how it references columns after UNNEST operations. I have been looking into unnest while working on a separate issue and from my limited knowledge, it might be because it needs an additional table alias assigned to the subquery because SQLAlchemy needs additional clarity about how to reference columns? It seems like adding that alias will solve your problem, but there are workarounds mentioned [here](https://stackoverflow.com/questions/52953606/sql-unnest-requires-alias) for example. Can you try that and let me know if it still doesn't work and I will look into it.

**Comment by aczire** [comment]
Thanks @kiraksi 

I tried adding the alias, `code_coding = db.query(func.unnest(self.model.code_coding).alias('cc')).subquery()`

But that still didnt work. Still got the KeyError, which means the unnest'd columns are still not in `c`.

Any idea?

Opened a discussion on the same here as well,
https://github.com/sqlalchemy/sqlalchemy/discussions/10779

**Comment by kiraksi** [comment]
I plan on taking a look at this issue next week. I see the sqlalchemy team had a suggested fix, @aczire did that work for you?

**Comment by aczire** [comment]
Thanks @kiraksi 
I couldn't get it done, so went with filtering it in the business logic instead of filtering it during the query phase. Any help is much appreciated!

**Comment by Linchin** [comment]
I think the answer over at https://github.com/sqlalchemy/sqlalchemy/discussions/10779 meant, instead of using `func.unnest(self.model.code_coding).alias('cc')` for alias, use `func.unnest(self.model.code_coding).table_valued("code", "display")` to essentially create new columns with the subfields' names. A small example for filtering unnested subfields:

```
from sqlalchemy import *
from sqlalchemy.engine import create_engine
from sqlalchemy.schema import *

engine = create_engine('bigquery://<project-name>')

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy_bigquery import STRUCT, ARRAY
Base = declarative_base()
class Wikidata(Base):
    __tablename__ = "bigquery-public-data.wikipedia.wikidata"
    
    id = Column(String, primary_key=True)
    labels = Column(ARRAY(
        [STRUCT(
        ("language", String),
        ("value", String),
    )]
    ), nullable=True)


sql = select([Wikidata.id, Column("language"), Column("value")])\
    .filter(Column("language") == "en")\
    .filter(Column("value") == "Top Gear")\
    .select_from(func.unnest(Wikidata.labels).table_valued("language", "value"))

print(sql)
result = engine.execute(sql).fetchall()
print(result)
```

I will close this issue for now, but please let us know if you have any further questions :)
